### ISSUE TITLE
Failed to load the archive-view package

### ISSUE THREAD

**Issue by chl1996** [atom/archive-view#26]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.11
**Thrown From**: [archive-view](https://github.com/atom/archive-view) package, v0.58.0

### Stack Trace

Failed to load the archive-view package

```
At Cannot find module '../build/Release/pathwatcher.node'

Error: Cannot find module '../build/Release/pathwatcher.node'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/chl/.atom/packages/archive-view/node_modules/pathwatcher/lib/main.js:6:13)
    at Object.<anonymous> (/Users/chl/.atom/packages/archive-view/node_modules/pathwatcher/lib/main.js:207:4)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
    at Module.load (module.js:347:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ],
    "disabledPackages": [
      "emmet",
      "emmet",
      "emmet",
      "emmet",
      "emmet",
      "emmet",
      "emmet",
      "emmet",
      "emmet",
      "emmet",
      "emmet",
      "emmet",
      "emmet",
      "emmet",
      "emmet",
      "emmet",
      "emmet",
      "emmet",
      "emmet"
    ]
  }
}
```

### Installed Packages

```coffee
# User
archive-view, v0.58.0
linter-jshint, v1.0.5
vim-mode, v0.55.0

# Dev
No dev packages
```

**Comment by thomasjo** [comment]
First of all, why have you installed `archive-view`? It comes bundled with Atom. Secondly, how did you install it? If you installed by cloning the Git repository and linking it via e.g. `apm link`, you need to run `apm install` from the repository to install required dependencies.

**Comment by chl1996** [comment]
谢谢

**Comment by 50Wliu** [comment]
> 谢谢

I'm assuming you've fixed your issue then, so I'm going to close this.  If you're still having problems, please comment here and I'll reopen it.
