### ISSUE TITLE
Failed to activate the archive-view package

### ISSUE THREAD

**Issue by avm94tom** [atom/archive-view#52]
[Enter steps to reproduce:]

1. Install package via atom installer
2. Close atom 
3. Run atom

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 7 home basic sp1
**Thrown From**: [archive-view](https://github.com/atom/archive-view) package 0.63.3

### Stack Trace

Failed to activate the archive-view package

```
At Cannot find module 'fs-plus'

Error: Cannot find module 'fs-plus'
  at Module._resolveFilename (module.js:455:15)
  at Module._resolveFilename (~/AppData/Local/atom/app-1.18.0/resources/electron.asar/common/reset-search-paths.js:35:12)
  at Function.get_Module._resolveFilename (<embedded>:8013:58)
  at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:40:43)
  at require (<embedded>:7358:33)
  at /packages/archive-view-master/lib/archive-editor.coffee:3:6)
  at /packages/archive-view-master/lib/archive-editor.coffee:1:1)
  at Module.get_Module._compile (<embedded>:7398:36)
  at Object.value [as .coffee] (<embedded>:7649:29)
  at Module.load (module.js:473:32)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:47:45)
  at require (internal/module.js:20:19)
  at customRequire (<embedded>:96:26)
  at Package.module.exports.Package.requireMainModule (<embedded>:69753:35)
  at Package.module.exports.Package.activateNow (<embedded>:69108:22)
  at <embedded>:69091:38
  at Package.module.exports.Package.measure (<embedded>:68965:21)
  at <embedded>:69084:32
  at Package.module.exports.Package.activate (<embedded>:69081:40)
  at PackageManager.module.exports.PackageManager.activatePackage (<embedded>:20537:40)
  at <embedded>:20518:35
  at Config.module.exports.Config.transactAsync (<embedded>:17608:24)
  at PackageManager.module.exports.PackageManager.activatePackages (<embedded>:20513:25)
  at PackageManager.module.exports.PackageManager.activate (<embedded>:20495:52)
  at <embedded>:1080:34

```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.30.3 
autocomplete-python 1.9.1 
kite 0.30.1 
python-tools 0.6.9 
```

**Comment by 50Wliu** [comment]
archive-view should not be installed manually as it is included with the default Atom installation.  If you uninstall it the bundled version will be used and you shouldn't run into this error.
